/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { CurrencyAmount } from "./currencyamount";
import { DocumentNumber } from "./documentnumber";
import { Tax } from "./tax";
import { Expose, Transform, Type } from "class-transformer";

export class AgencyServiceFee extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "@type" })
    atType: string;

    /**
     * A monetary amount, up to 4 decimal places. Decimal place needs to be included.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "Amount" })
    @Type(() => CurrencyAmount)
    amount: CurrencyAmount;

    /**
     * The description of the service fee
     */
    @SpeakeasyMetadata()
    @Expose({ name: "Description" })
    description?: string;

    /**
     * The service fee expiry date. Once expiry date has been reached, the service fee information will only be stored in the ReservationReceipt
     */
    @SpeakeasyMetadata()
    @Expose({ name: "ExpiryDate" })
    @Transform(({ value }) => new Date(value), { toClassOnly: true })
    expiryDate?: Date;

    /**
     * Reference to an Offer within the Reservation that this service fee applies to
     */
    @SpeakeasyMetadata()
    @Expose({ name: "OfferRef" })
    offerRef?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "RelatedDocumentNumber" })
    @Type(() => DocumentNumber)
    relatedDocumentNumber?: DocumentNumber;

    @SpeakeasyMetadata({ elemType: Tax })
    @Expose({ name: "Tax" })
    @Type(() => Tax)
    tax?: Tax[];

    /**
     * Reference to a Traveler within the Reservation that this service fee applies to
     */
    @SpeakeasyMetadata()
    @Expose({ name: "TravelerRef" })
    travelerRef?: string;

    /**
     * Unique id for this object within a message
     */
    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id?: string;
}
