/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class AgencyServiceFeeIdentifier extends SpeakeasyBase {
    /**
     * Unique id for this object within a message
     */
    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id?: string;
}
