/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { CurrencyCode } from "./currencycode";
import { CurrencySourceEnum } from "./currencysourceenum";
import { Fees } from "./fees";
import { Taxes } from "./taxes";
import { Expose, Type } from "class-transformer";

export class Amount extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "@type" })
    atType?: string;

    /**
     * The price prior to all applicable taxes of a product such as the rate for a room or fare for a flight.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "Base" })
    base?: number;

    /**
     * Currency codes are the three-letter alphabetic codes that represent the various currencies used throughout the world.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "CurrencyCode" })
    @Type(() => CurrencyCode)
    currencyCode?: CurrencyCode;

    @SpeakeasyMetadata()
    @Expose({ name: "Fees" })
    @Type(() => Fees)
    fees?: Fees;

    @SpeakeasyMetadata()
    @Expose({ name: "Taxes" })
    @Type(() => Taxes)
    taxes?: Taxes;

    /**
     * Specifies the total price including base + taxes + fees
     */
    @SpeakeasyMetadata()
    @Expose({ name: "Total" })
    total?: number;

    /**
     * True if this amount has been converted from the original amount
     */
    @SpeakeasyMetadata()
    @Expose({ name: "approximateInd" })
    approximateInd?: boolean;

    /**
     * The system requesting or returning the currency code specified in the attribute
     */
    @SpeakeasyMetadata()
    @Expose({ name: "currencySource" })
    currencySource?: CurrencySourceEnum;
}
