/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * Identifies the availability status of an item.
 */
export enum AvailabilityStatusEnum {
    Open = "Open",
    Close = "Close",
    ClosedOnArrival = "ClosedOnArrival",
    ClosedOnArrivalOnRequest = "ClosedOnArrivalOnRequest",
    OnRequest = "OnRequest",
    RemoveCloseOnly = "RemoveCloseOnly",
    Other = "Other",
}
