/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * Specifies the cabin type (e.g. first, business, economy).
 */
export enum CabinAirEnum {
    PremiumFirst = "PremiumFirst",
    First = "First",
    Business = "Business",
    PremiumEconomy = "PremiumEconomy",
    Economy = "Economy",
}
