/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { CatalogOfferingsQueryBuildFromProperties } from "./catalogofferingsquerybuildfromproperties";
import { Expose, Type } from "class-transformer";

export class CatalogOfferingsQueryBuildFromPropertiesWrapper extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "CatalogOfferingsQueryBuildFromProperties" })
    @Type(() => CatalogOfferingsQueryBuildFromProperties)
    catalogOfferingsQueryBuildFromProperties?: CatalogOfferingsQueryBuildFromProperties;
}
