/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { CatalogOfferingsQueryRequest } from "./catalogofferingsqueryrequest";
import { Expose, Type } from "class-transformer";

export class CatalogOfferingsQueryRequestHospitalityWrapper extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "CatalogOfferingsQueryRequest" })
    @Type(() => CatalogOfferingsQueryRequest)
    catalogOfferingsQueryRequest?: CatalogOfferingsQueryRequest;
}
