/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { CatalogOfferingsRequestHospitality } from "./catalogofferingsrequesthospitality";
import { Expose, Type } from "class-transformer";

export class CatalogOfferingsQueryRequest extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "@type" })
    atType: string;

    @SpeakeasyMetadata({ elemType: CatalogOfferingsRequestHospitality })
    @Expose({ name: "CatalogOfferingsRequest" })
    @Type(() => CatalogOfferingsRequestHospitality)
    catalogOfferingsRequest: CatalogOfferingsRequestHospitality[];
}
