/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { BuildFromProperties } from "./buildfromproperties";
import { Expose, Type } from "class-transformer";

export class CatalogOfferingsQueryBuildFromProperties extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "@type" })
    atType?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "BuildFromCatalogOfferingHospitality" })
    @Type(() => BuildFromProperties)
    buildFromCatalogOfferingHospitality?: BuildFromProperties;
}
