/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { CurrencyAmount } from "./currencyamount";
import { DateOrDateWindows } from "./dateordatewindows";
import { HotelSearchCriterion } from "./hotelsearchcriterion";
import { SearchControlConsoleChannelID } from "./searchcontrolconsolechannelid";
import { Expose, Type } from "class-transformer";

export class CatalogOfferingsRequestHospitality extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "@type" })
    atType?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "HotelSearchCriterion" })
    @Type(() => HotelSearchCriterion)
    hotelSearchCriterion?: HotelSearchCriterion;

    /**
     * A monetary amount, up to 4 decimal places. Decimal place needs to be included.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "MaximumAmount" })
    @Type(() => CurrencyAmount)
    maximumAmount?: CurrencyAmount;

    /**
     * A monetary amount, up to 4 decimal places. Decimal place needs to be included.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "MinimumAmount" })
    @Type(() => CurrencyAmount)
    minimumAmount?: CurrencyAmount;

    @SpeakeasyMetadata()
    @Expose({ name: "SearchControlConsoleChannelID" })
    @Type(() => SearchControlConsoleChannelID)
    searchControlConsoleChannelID?: SearchControlConsoleChannelID;

    /**
     * Indicates the expiry date.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "StayDates" })
    @Type(() => DateOrDateWindows)
    stayDates: DateOrDateWindows;

    /**
     * Maximum time (in milliseconds) to wait for provider responses before returning a response to the consumer of this service
     */
    @SpeakeasyMetadata()
    @Expose({ name: "maxResponseWaitTime" })
    maxResponseWaitTime?: number;

    /**
     * You can use requested currency to request conversion rate information. The response will return the currencyRateConversion object which will contain conversion rate of the requested currency.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "requestedCurrency" })
    requestedCurrency?: string;

    /**
     * Used to specify that a verbose response is to be returned.  Verbose responses repeat the Property information in each Product and do not return the reference list.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "verboseResponseInd" })
    verboseResponseInd?: boolean;
}
