/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { CatalogOfferingsHospitalityResponse } from "./catalogofferingshospitalityresponse";
import { Expose, Type } from "class-transformer";

export class CatalogOfferingsHospitalityResponseWrapper extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "CatalogOfferingsHospitalityResponse" })
    @Type(() => CatalogOfferingsHospitalityResponse)
    catalogOfferingsHospitalityResponse?: CatalogOfferingsHospitalityResponse;
}
