/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { TextTitleAndDescription } from "./texttitleanddescription";
import { Expose, Type } from "class-transformer";

export class CheckInOutPolicy extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "@type" })
    atType?: string;

    @SpeakeasyMetadata({ elemType: TextTitleAndDescription })
    @Expose({ name: "Description" })
    @Type(() => TextTitleAndDescription)
    description?: TextTitleAndDescription[];

    /**
     * Check-in time
     */
    @SpeakeasyMetadata()
    @Expose({ name: "checkInTime" })
    checkInTime: string;

    /**
     * Check-out time
     */
    @SpeakeasyMetadata()
    @Expose({ name: "checkOutTime" })
    checkOutTime: string;

    /**
     * Minimum age of guest checking in or out
     */
    @SpeakeasyMetadata()
    @Expose({ name: "minimumAge" })
    minimumAge?: number;
}
