/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * Type of commission
 */
export enum CommissionEnum {
    Full = "Full",
    Partial = "Partial",
    NonPaying = "Non-paying",
    NoShow = "No-show",
    Adjustment = "Adjustment",
    Commissionable = "Commissionable",
}
