/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * Identifies a company by name.
 */
export class CompanyName extends SpeakeasyBase {
    /**
     * Identifies a company by the company code
     */
    @SpeakeasyMetadata()
    @Expose({ name: "code" })
    code?: string;

    /**
     * Identifies the context of the identifying code,such as DUNS,IATA or internal code
     */
    @SpeakeasyMetadata()
    @Expose({ name: "codeContext" })
    codeContext?: string;

    /**
     * The department name or ID with which the contact is associated
     */
    @SpeakeasyMetadata()
    @Expose({ name: "department" })
    department?: string;

    /**
     * The division name or ID with which the contact is associated
     */
    @SpeakeasyMetadata()
    @Expose({ name: "division" })
    division?: string;

    /**
     * Use this id to internally identify this company in NextSteps
     */
    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id?: string;

    /**
     * Used to provide the company common name
     */
    @SpeakeasyMetadata()
    @Expose({ name: "shortName" })
    shortName?: string;

    /**
     * The system(s) that maintain the data
     */
    @SpeakeasyMetadata()
    @Expose({ name: "systemOfRecord" })
    systemOfRecord?: string[];

    @SpeakeasyMetadata()
    @Expose({ name: "value" })
    value?: string;
}
