/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * Status returned in a response for a two or more phase commitment process
 */
export enum ConfirmationStatusEnum {
    Pending = "Pending",
    Confirmed = "Confirmed",
    Cancelled = "Cancelled",
    Rejected = "Rejected",
}
