/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose, Transform } from "class-transformer";

/**
 * A conversion metric from standard to another with the contextual authority such as IATA, OAG, ISO, etc.
 */
export class ConversionRate extends SpeakeasyBase {
    /**
     * Rate as of
     */
    @SpeakeasyMetadata()
    @Expose({ name: "rateAsOf" })
    @Transform(({ value }) => new Date(value), { toClassOnly: true })
    rateAsOf?: Date;

    /**
     * Rate authority
     */
    @SpeakeasyMetadata()
    @Expose({ name: "rateAuthority" })
    rateAuthority?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "value" })
    value?: number;
}
