/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * ISO 3166 code for a country with optional name
 */
export class Country extends SpeakeasyBase {
    /**
     * The source of a code
     */
    @SpeakeasyMetadata()
    @Expose({ name: "codeContext" })
    codeContext?: string;

    /**
     * Use this id to internally identify this country in NextSteps
     */
    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id?: string;

    /**
     * The name or code of a country
     */
    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "value" })
    value?: string;
}
