/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * The system requesting or returning the currency code specified in the attribute
 */
export enum CurrencySourceEnum {
    Supplier = "Supplier",
    Charged = "Charged",
    Requested = "Requested",
}
