/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * Specifies the ID for the membership program.
 */
export class CustomerLoyalty extends SpeakeasyBase {
    /**
     * The card holder name
     */
    @SpeakeasyMetadata()
    @Expose({ name: "cardHolderName" })
    cardHolderName?: string;

    /**
     * Customer Loyality Id
     */
    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id?: string;

    /**
     * Numeric Priority Code
     */
    @SpeakeasyMetadata()
    @Expose({ name: "priority" })
    priority?: number;

    /**
     * Specifies an identifier to indicate the company owner of the loyalty program
     */
    @SpeakeasyMetadata()
    @Expose({ name: "programId" })
    programId?: string;

    /**
     * Supplier's loyalty program name such as Frontier-EarlyReturns
     */
    @SpeakeasyMetadata()
    @Expose({ name: "programName" })
    programName?: string;

    /**
     * The list of suppliers that the CustomerLoyalty number is shared.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "shareWithSupplier" })
    shareWithSupplier?: string[];

    /**
     * Supplier of a loyalty program
     */
    @SpeakeasyMetadata()
    @Expose({ name: "supplier" })
    supplier?: string;

    /**
     * The kind of supplier of a loyalty program
     */
    @SpeakeasyMetadata()
    @Expose({ name: "supplierType" })
    supplierType?: string;

    /**
     * Customer Loyalty tier level
     */
    @SpeakeasyMetadata()
    @Expose({ name: "tier" })
    tier?: string;

    /**
     * Customer loyalty number has been validated by the supplier
     */
    @SpeakeasyMetadata()
    @Expose({ name: "validatedInd" })
    validatedInd?: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "value" })
    value?: string;
}
