/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { CustomerLoyalty } from "./customerloyalty";
import { Expose, Type } from "class-transformer";

export class CustomerLoyaltyCredit extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "@type" })
    atType?: string;

    /**
     * Specifies the ID for the membership program.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "CustomerLoyalty" })
    @Type(() => CustomerLoyalty)
    customerLoyalty: CustomerLoyalty;

    /**
     * Represents the amount of award credit awarded for this offer\/offering. Award credit can be used for purchasing goods and services through a customer loyalty program
     */
    @SpeakeasyMetadata()
    @Expose({ name: "Earned" })
    earned: string;

    /**
     * Represents the amount of status credit awarded for this offer\/offering. Status credit allow a customer to move up the ladder of a customer loyalty program
     */
    @SpeakeasyMetadata()
    @Expose({ name: "Status" })
    status: string;
}
