/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

export enum DestinationEnum {
    UnitedStatesOfAmerica = "United States of America",
    MexicoCentralAmericaCanalZoneCostaRica = "Mexico / Central America / Canal Zone/ Costa Rica",
    IslandsAndCountriesOfTheCaribbean = "Islands and Countries of the Caribbean",
    SouthAmerica = "South America",
    Europe = "Europe",
    Africa = "Africa",
    MiddleEastWesternAsia = "Middle East / Western Asia",
    Asia = "Asia",
    AustraliaNewZealandPacificIslands = "Australia / New Zealand / Pacific Islands",
    CanadaAndGreenland = "Canada and Greenland",
}
