/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * Codes from OTA DOC - Document Type
 */
export enum DocTypeCodeEnum {
    Visa = "Visa",
    Passport = "Passport",
    MilitaryIdentification = "MilitaryIdentification",
    DriversLicense = "DriversLicense",
    NationalIdentityDocument = "NationalIdentityDocument",
    VaccinationCertificate = "VaccinationCertificate",
    AlienRegistrationNumber = "AlienRegistrationNumber",
    InsurancePolicyNumber = "InsurancePolicyNumber",
    TaxExemptionNumber = "TaxExemptionNumber",
    VehicleRegistrationLicenseNumber = "VehicleRegistrationLicenseNumber",
    BoderCrossingCard = "BoderCrossingCard",
    RefugeeTravelDocument = "RefugeeTravelDocument",
    PilotsLicense = "PilotsLicense",
    PermanentResidentCard = "PermanentResidentCard",
    RedressNumber = "RedressNumber",
    KnownTravelerNumber = "KnownTravelerNumber",
    NonStandard = "Non-Standard",
    MerchantNumber = "MerchantNumber",
    AirNexusCard = "AirNexusCard",
    CrewMemberCertificate = "CrewMemberCertificate",
    PassportCard = "PassportCard",
    NaturalizationCertificate = "NaturalizationCertificate",
    TicketNumber = "TicketNumber",
    LargeFamilyDiscountCard = "LargeFamilyDiscountCard",
}
