/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { ChangeFeeCollectionMethod } from "./changefeecollectionmethod";
import { Commissions } from "./commissions";
import { DestinationPurpose } from "./destinationpurpose";
import { Identifier } from "./identifier";
import { NetRemitInfo } from "./netremitinfo";
import { OfferIdentifier } from "./offeridentifier";
import { ProductIdentifier } from "./productidentifier";
import { Restrictions } from "./restrictions";
import { TicketDesignators } from "./ticketdesignators";
import { TourCodes } from "./tourcodes";
import { Expose, Type } from "class-transformer";

export class DocumentOverrides extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "@type" })
    atType: string;

    @SpeakeasyMetadata()
    @Expose({ name: "ChangeFeeCollectionMethod" })
    @Type(() => ChangeFeeCollectionMethod)
    changeFeeCollectionMethod?: ChangeFeeCollectionMethod;

    @SpeakeasyMetadata({ elemType: Commissions })
    @Expose({ name: "Commissions" })
    @Type(() => Commissions)
    commissions?: Commissions[];

    @SpeakeasyMetadata({ elemType: DestinationPurpose })
    @Expose({ name: "DestinationPurpose" })
    @Type(() => DestinationPurpose)
    destinationPurpose?: DestinationPurpose[];

    @SpeakeasyMetadata()
    @Expose({ name: "DocumentOverridesRef" })
    documentOverridesRef?: string;

    /**
     * Identifier provides the ability to create a globally unique identifier. For the identifier to be globally unique it must have a system provided identifier and the system must be identified using a global naming authority. System identification uses the domain naming system (DNS) to assure they are globally unique and should be an URL. The system provided ID will typically be a primary or surrogate key in a database.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "Identifier" })
    @Type(() => Identifier)
    identifier?: Identifier;

    @SpeakeasyMetadata()
    @Expose({ name: "NetRemitInfo" })
    @Type(() => NetRemitInfo)
    netRemitInfo?: NetRemitInfo;

    @SpeakeasyMetadata()
    @Expose({ name: "OfferIdentifier" })
    @Type(() => OfferIdentifier)
    offerIdentifier?: OfferIdentifier;

    @SpeakeasyMetadata()
    @Expose({ name: "ProductIdentifier" })
    @Type(() => ProductIdentifier)
    productIdentifier?: ProductIdentifier;

    @SpeakeasyMetadata({ elemType: Restrictions })
    @Expose({ name: "Restrictions" })
    @Type(() => Restrictions)
    restrictions?: Restrictions[];

    @SpeakeasyMetadata({ elemType: TicketDesignators })
    @Expose({ name: "TicketDesignators" })
    @Type(() => TicketDesignators)
    ticketDesignators?: TicketDesignators[];

    @SpeakeasyMetadata({ elemType: TourCodes })
    @Expose({ name: "TourCodes" })
    @Type(() => TourCodes)
    tourCodes?: TourCodes[];

    /**
     * The reporting number.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id?: string;
}
