/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { DocumentTypeEnum } from "./documenttypeenum";
import { Expose } from "class-transformer";

export class DocumentNumber extends SpeakeasyBase {
    /**
     * Document issuer
     */
    @SpeakeasyMetadata()
    @Expose({ name: "documentIssuer" })
    documentIssuer?: string;

    /**
     * Document type like EMD, MCO
     */
    @SpeakeasyMetadata()
    @Expose({ name: "documentType" })
    documentType?: DocumentTypeEnum;

    @SpeakeasyMetadata()
    @Expose({ name: "value" })
    value?: string;
}
