/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * Document type like EMD, MCO
 */
export enum DocumentTypeEnum {
    Emd = "EMD",
    Mco = "MCO",
    Ticket = "Ticket",
}
