/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * Defines the Units that can be applied to Stay restrictions.
 */
export enum DurationUnitEnum {
    Minutes = "Minutes",
    Hours = "Hours",
    Days = "Days",
    Months = "Months",
    Mon = "MON",
    Tues = "TUES",
    Wed = "WED",
    Thu = "THU",
    Fri = "FRI",
    Sat = "SAT",
    Sun = "SUN",
}
