/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

export enum EnumTelephoneRole {
    Mobile = "Mobile",
    Home = "Home",
    Work = "Work",
    Office = "Office",
    Fax = "Fax",
    Other = "Other",
}
