/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

export enum EnumAddressRole {
    Home = "Home",
    Business = "Business",
    Mailing = "Mailing",
    Delivery = "Delivery",
    Destination = "Destination",
    Other = "Other",
    Billing = "Billing",
}
