/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

export enum FareQualifierENUMBase {
    Consolidator = "Consolidator",
    Government = "Government",
    Marine = "Marine",
    Military = "Military",
    Reward = "Reward",
    StandBy = "StandBy",
    Staff = "Staff",
    Student = "Student",
    Tour = "Tour",
    Youth = "Youth",
    VistFriendsAndRelatives = "VistFriendsAndRelatives",
}
