/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * Defines the type of fares to return (Only public fares, Only private fares, Only agency private fares, Only
 */
export enum FareTypeEnum {
    PublicFare = "PublicFare",
    AgencyPrivateFare = "AgencyPrivateFare",
    AirlinePrivateFare = "AirlinePrivateFare",
    NetFare = "NetFare",
}
