/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * The base amount of a ticket price or net price that is filed in local currency
 */
export class FiledAmount extends SpeakeasyBase {
    /**
     * Filed amount currency code authority
     */
    @SpeakeasyMetadata()
    @Expose({ name: "codeAuthority" })
    codeAuthority: string;

    /**
     * Filed amount currency code
     */
    @SpeakeasyMetadata()
    @Expose({ name: "currencyCode" })
    currencyCode?: string;

    /**
     * ISO 4217 standard decimal authority
     */
    @SpeakeasyMetadata()
    @Expose({ name: "decimalAuthority" })
    decimalAuthority?: string;

    /**
     * ISO 4217 standard has a different number of decimals
     */
    @SpeakeasyMetadata()
    @Expose({ name: "decimalPlace" })
    decimalPlace: number;

    /**
     * Filed amount value
     */
    @SpeakeasyMetadata()
    @Expose({ name: "value" })
    value?: number;
}
