/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * Gender Type Male, Female etc. This field is not used by Hotel APIs and will be ignored
 */
export enum GenderEnum {
    Male = "Male",
    Female = "Female",
    Unknown = "Unknown",
    Undisclosed = "Undisclosed",
}
