/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class GuestCount extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "@type" })
    atType?: string;

    /**
     * The age of the guest
     */
    @SpeakeasyMetadata()
    @Expose({ name: "age" })
    age?: number;

    /**
     * Enter 10 for an adult or 08 for a child
     */
    @SpeakeasyMetadata()
    @Expose({ name: "ageQualifyingCode" })
    ageQualifyingCode?: string;

    /**
     * The number of guests in one AgeQualifyingCode or Count.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "count" })
    count?: number;
}
