/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * The method to be used in sorting hotel properties
 */
export enum HotelSortOrderEnum {
    StarRating = "StarRating",
    Proximity = "Proximity",
}
