/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

export enum HotelAggregatorEnum {
    Travelport = "Travelport",
    Agoda = "Agoda",
    Booking = "Booking",
    Expedia = "Expedia",
    Bonotel = "Bonotel",
}
