/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

export enum IdentifierTypeENUM {
    Reservation = "Reservation",
    Locator = "Locator",
    SupplierLocator = "SupplierLocator",
    DocumentNumber = "DocumentNumber",
}
