/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * Indicates the size of the image. Hospitality APIs no longer support thumbnail
 */
export enum ImageSizeEnum {
    Large = "Large",
    Medium = "Medium",
    Small = "Small",
    Thumbnail = "Thumbnail",
    ExtraLarge = "ExtraLarge",
}
