/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { ImageSizeEnum } from "./imagesizeenum";
import { PictureofEnum } from "./pictureofenum";
import { Expose } from "class-transformer";

/**
 * URL of the image
 */
export class Image extends SpeakeasyBase {
    /**
     * Image title
     */
    @SpeakeasyMetadata()
    @Expose({ name: "caption" })
    caption?: string;

    /**
     * Deprecated and replaced by Image Size
     */
    @SpeakeasyMetadata()
    @Expose({ name: "dimensionCategory" })
    dimensionCategory?: string;

    /**
     * Height
     */
    @SpeakeasyMetadata()
    @Expose({ name: "height" })
    height?: number;

    /**
     * Indicates the size of the image. Hospitality APIs no longer support thumbnail
     */
    @SpeakeasyMetadata()
    @Expose({ name: "imageSize" })
    imageSize?: ImageSizeEnum;

    /**
     * deprecated and replaced by pictureOf
     */
    @SpeakeasyMetadata()
    @Expose({ name: "pictureCategory" })
    pictureCategory?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "pictureOf" })
    pictureOf?: PictureofEnum;

    @SpeakeasyMetadata()
    @Expose({ name: "value" })
    value?: string;

    /**
     * Width of image
     */
    @SpeakeasyMetadata()
    @Expose({ name: "width" })
    width?: number;
}
