/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * Maximum Available Rate for this Property, including the authority who provided the rate if it is different from the PropertyInfo authority.
 */
export class MaximumAvailableRate extends SpeakeasyBase {
    /**
     * Name of the authoritative system that provided this rate
     */
    @SpeakeasyMetadata()
    @Expose({ name: "authority" })
    authority?: string;

    /**
     * An ISO 4217 alpha character code that specifies a money unit
     */
    @SpeakeasyMetadata()
    @Expose({ name: "code" })
    code?: string;

    /**
     * Minor units are a mechanism for expressing the relationship between a major currency unit and its corresponding minor currency unit.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "minorUnit" })
    minorUnit?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "value" })
    value?: number;
}
