/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * Indicates if a meal is included
 */
export class MealsIncluded extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "breakfastInd" })
    breakfastInd?: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "dinnerInd" })
    dinnerInd?: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "lunchInd" })
    lunchInd?: boolean;
}
