/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { MeasurementTypeEnum } from "./measurementtypeenum";
import { UnitOfMeasureEnum } from "./unitofmeasureenum";
import { Expose } from "class-transformer";

/**
 * Used for dimensional units (width, height, depth) or weight
 */
export class Measurement extends SpeakeasyBase {
    /**
     * The type of measurement such as width, height, weight
     */
    @SpeakeasyMetadata()
    @Expose({ name: "measurementType" })
    measurementType?: MeasurementTypeEnum;

    /**
     * The unit of measure in a code format. Refer to OpenTravel Code List Unit of Measure Code (UOM).
     */
    @SpeakeasyMetadata()
    @Expose({ name: "unit" })
    unit?: UnitOfMeasureEnum;

    @SpeakeasyMetadata()
    @Expose({ name: "value" })
    value?: number;
}
