/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * The type of measurement such as width, height, weight
 */
export enum MeasurementTypeEnum {
    Width = "Width",
    Height = "Height",
    Depth = "Depth",
    Weight = "Weight",
    OverallDimension = "OverallDimension",
}
