/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { UnitOfSize } from "./unitofsize";
import { Expose } from "class-transformer";

export class MeetingRoom extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "@type" })
    atType?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "capacity" })
    capacity?: number;

    /**
     * OTA code for this room type.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "codes" })
    codes?: string[];

    /**
     * The name of the meeting room
     */
    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name: string;

    @SpeakeasyMetadata()
    @Expose({ name: "size" })
    size?: number;

    /**
     * List of units of size i.e Square Feet, Square Meters
     */
    @SpeakeasyMetadata()
    @Expose({ name: "unitOfSize" })
    unitOfSize?: UnitOfSize;
}
