/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { NextStep } from "./nextstep";
import { Expose, Type } from "class-transformer";

export class NextSteps extends SpeakeasyBase {
    @SpeakeasyMetadata({ elemType: NextStep })
    @Expose({ name: "NextStep" })
    @Type(() => NextStep)
    nextStep: NextStep[];

    /**
     * The base portion of the uri in order to shorten the uri's in the individual steps
     */
    @SpeakeasyMetadata()
    @Expose({ name: "baseURI" })
    baseURI: string;

    /**
     * Optional internally referenced id
     */
    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id?: string;
}
