/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * Describes the set of potential methods that can be taken after an operation.
 */
export enum NextStepMethodEnum {
    Get = "GET",
    Delete = "DELETE",
    Put = "PUT",
    Post = "POST",
}
