/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { RFCDate } from "../../types";
import { HotelAggregatorEnum } from "./hotelaggregatorenum";
import { PropertyKey } from "./propertykey";
import { RateCandidate } from "./ratecandidate";
import { RoomStayCandidates } from "./roomstaycandidates";
import { Expose, Transform, Type } from "class-transformer";

export class OfferQueryHospitalityRequest extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "@type" })
    atType: string;

    @SpeakeasyMetadata()
    @Expose({ name: "HotelAggregator" })
    hotelAggregator?: HotelAggregatorEnum;

    @SpeakeasyMetadata()
    @Expose({ name: "PropertyKey" })
    @Type(() => PropertyKey)
    propertyKey: PropertyKey;

    @SpeakeasyMetadata()
    @Expose({ name: "RateCandidate" })
    @Type(() => RateCandidate)
    rateCandidate?: RateCandidate;

    @SpeakeasyMetadata()
    @Expose({ name: "RoomStayCandidates" })
    @Type(() => RoomStayCandidates)
    roomStayCandidates?: RoomStayCandidates;

    /**
     * The booking code
     */
    @SpeakeasyMetadata()
    @Expose({ name: "bookingCode" })
    bookingCode?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "checkinDate" })
    @Type(() => String)
    @Transform(({ value }) => new RFCDate(value), { toClassOnly: true })
    checkinDate: RFCDate;

    @SpeakeasyMetadata()
    @Expose({ name: "checkoutDate" })
    @Type(() => String)
    @Transform(({ value }) => new RFCDate(value), { toClassOnly: true })
    checkoutDate: RFCDate;

    /**
     * The number of guests
     */
    @SpeakeasyMetadata()
    @Expose({ name: "numberOfGuests" })
    numberOfGuests: number;

    /**
     * You can use requested currency to request conversion rate information. The response will return the currencyRateConversion object which will contain conversion rate of the requested currency.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "requestedCurrency" })
    requestedCurrency?: string;

    /**
     * stored amount
     */
    @SpeakeasyMetadata()
    @Expose({ name: "storedAmount" })
    storedAmount?: number;

    /**
     * stored currency
     */
    @SpeakeasyMetadata()
    @Expose({ name: "storedCurrency" })
    storedCurrency?: string;
}
