/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { OfferHospitalityResponse } from "./offerhospitalityresponse";
import { Expose, Type } from "class-transformer";

export class OfferHospitalityResponseWrapper extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "OfferHospitalityResponse" })
    @Type(() => OfferHospitalityResponse)
    offerHospitalityResponse?: OfferHospitalityResponse;
}
