/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { OfferQueryHospitalityRequest } from "./offerqueryhospitalityrequest";
import { Expose, Type } from "class-transformer";

export class OfferQueryHospitalityRequestWrapper extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "OfferQueryHospitalityRequest" })
    @Type(() => OfferQueryHospitalityRequest)
    offerQueryHospitalityRequest?: OfferQueryHospitalityRequest;
}
