/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { OfferQueryBuildFromCatalogOffering } from "./offerquerybuildfromcatalogoffering";
import { Expose, Type } from "class-transformer";

export class OfferQueryBuildFromCatalogOfferingWrapper extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "OfferQueryBuildFromCatalogOffering" })
    @Type(() => OfferQueryBuildFromCatalogOffering)
    offerQueryBuildFromCatalogOffering?: OfferQueryBuildFromCatalogOffering;
}
