/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { BuildFromCatalogOfferingsRequest } from "./buildfromcatalogofferingsrequest";
import { Expose, Type } from "class-transformer";

export class OfferQueryBuildFromCatalogOfferingsHospitality extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "@type" })
    atType: string;

    @SpeakeasyMetadata()
    @Expose({ name: "BuildFromCatalogOfferingsRequest" })
    @Type(() => BuildFromCatalogOfferingsRequest)
    buildFromCatalogOfferingsRequest?: BuildFromCatalogOfferingsRequest;
}
