/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { OfferQueryBuildFromCatalogOfferingsHospitality } from "./offerquerybuildfromcatalogofferingshospitality";
import { Expose, Type } from "class-transformer";

export class OfferQueryBuildFromCatalogOfferingsHospitalityWrapper extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "OfferQueryBuildFromCatalogOfferingsHospitality" })
    @Type(() => OfferQueryBuildFromCatalogOfferingsHospitality)
    offerQueryBuildFromCatalogOfferingsHospitality?: OfferQueryBuildFromCatalogOfferingsHospitality;
}
