/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

export enum OperationalStatusENUMBase {
    FlightBoarding = "FlightBoarding",
    FlightCancelled = "FlightCancelled",
    FlightDeparted = "FlightDeparted",
    FlightPastScheduledDeparture = "FlightPastScheduledDeparture",
    NotAvailableUseSearch = "NotAvailableUseSearch",
}
