/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { OperationalStatusENUMBase } from "./operationalstatusenumbase";
import { Expose } from "class-transformer";

export class OperationalStatusENUM extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "value" })
    value?: OperationalStatusENUMBase;
}
