/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * Used to indicate marketing preferences, OptIn, OptOut
 */
export enum OptInStatusEnum {
    OptedIn = "OptedIn",
    OptedOut = "OptedOut",
    Unknown = "Unknown",
}
