/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * The type of organization such as an Agency, Branch, Company, Supplier, Provider
 */
export enum OrganizationTypeEnum {
    TravelAgency = "TravelAgency",
    AgencyBranch = "AgencyBranch",
    LoyaltyProgram = "LoyaltyProgram",
    IdDocumentIssuer = "IdDocumentIssuer",
    TravelSupplier = "TravelSupplier",
    TravelProvider = "TravelProvider",
    Regulatory = "Regulatory",
}
