/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { FlightProduct } from "./flightproduct";
import { Expose, Type } from "class-transformer";

export class PassengerFlight extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "@type" })
    atType?: string;

    @SpeakeasyMetadata({ elemType: FlightProduct })
    @Expose({ name: "FlightProduct" })
    @Type(() => FlightProduct)
    flightProduct?: FlightProduct[];

    /**
     * Number of passengers of the specified passenger type code
     */
    @SpeakeasyMetadata()
    @Expose({ name: "passengerQuantity" })
    passengerQuantity?: number;

    /**
     * Passenger type code
     */
    @SpeakeasyMetadata()
    @Expose({ name: "passengerTypeCode" })
    passengerTypeCode?: string;
}
