/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class PersonName extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "@type" })
    atType: string;

    /**
     * Given name, first name or names.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "Given" })
    given?: string;

    /**
     * The middle name of the person name.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "Middle" })
    middle?: string;

    /**
     * Salutation of honorific (e.g. Mr., Mrs., Ms., Miss, Dr.)
     */
    @SpeakeasyMetadata()
    @Expose({ name: "Prefix" })
    prefix?: string;

    /**
     * Family name, last name.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "Surname" })
    surname: string;
}
