/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { TextTitleAndDescription } from "./texttitleanddescription";
import { YesNoUnknownEnum } from "./yesnounknownenum";
import { Expose, Type } from "class-transformer";

export class PetPolicy extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "@type" })
    atType?: string;

    /**
     * Descriptive text
     */
    @SpeakeasyMetadata()
    @Expose({ name: "Description" })
    @Type(() => TextTitleAndDescription)
    description?: TextTitleAndDescription;

    /**
     * Yes , No , Unknown
     */
    @SpeakeasyMetadata()
    @Expose({ name: "allowed" })
    allowed: YesNoUnknownEnum;

    /**
     * Pet policy code
     */
    @SpeakeasyMetadata()
    @Expose({ name: "policyCode" })
    policyCode?: string;
}
