/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * Specifies the level of accuracy for the position
 */
export enum PositionAccuracyEnum {
    Zip9Code = "Zip9Code",
    Zip7Code = "Zip7Code",
    Zip5Code = "Zip5Code",
    Street = "Street",
    State = "State",
    Property = "Property",
    Intersection = "Intersection",
    Exact = "Exact",
    County = "County",
    City = "City",
    Block = "Block",
}
