/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { AppliesTo } from "./appliesto";
import { TravelerIdentifier } from "./traveleridentifier";
import { Expose, Type } from "class-transformer";

export class Preference extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "@type" })
    atType: string;

    @SpeakeasyMetadata()
    @Expose({ name: "AppliesTo" })
    @Type(() => AppliesTo)
    appliesTo?: AppliesTo;

    @SpeakeasyMetadata()
    @Expose({ name: "TravelerIdentifier" })
    @Type(() => TravelerIdentifier)
    travelerIdentifier?: TravelerIdentifier;

    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id?: string;
}
