/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { CurrencyCode } from "./currencycode";
import { PriceBreakdown } from "./pricebreakdown";
import { VendorCurrencyTotal } from "./vendorcurrencytotal";
import { Expose, Type } from "class-transformer";

export class PriceDetail extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "@type" })
    atType: string;

    /**
     * The total amount not including taxes and\/or fees
     */
    @SpeakeasyMetadata()
    @Expose({ name: "Base" })
    base?: number;

    /**
     * Currency codes are the three-letter alphabetic codes that represent the various currencies used throughout the world.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "CurrencyCode" })
    @Type(() => CurrencyCode)
    currencyCode?: CurrencyCode;

    @SpeakeasyMetadata({ elemType: PriceBreakdown })
    @Expose({ name: "PriceBreakdown" })
    @Type(() => PriceBreakdown)
    priceBreakdown?: PriceBreakdown[];

    /**
     * The total of the fees included in the total price
     */
    @SpeakeasyMetadata()
    @Expose({ name: "TotalFees" })
    totalFees?: number;

    /**
     * The total price of the product in the currency indicated
     */
    @SpeakeasyMetadata()
    @Expose({ name: "TotalPrice" })
    totalPrice?: number;

    /**
     * The total of the taxes included in the total price
     */
    @SpeakeasyMetadata()
    @Expose({ name: "TotalTaxes" })
    totalTaxes?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "VendorCurrencyTotal" })
    @Type(() => VendorCurrencyTotal)
    vendorCurrencyTotal?: VendorCurrencyTotal;

    /**
     * Internally referenced id
     */
    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id?: string;
}
