/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Email } from "./email";
import { ShareWithEnum } from "./sharewithenum";
import { Telephone } from "./telephone";
import { TravelerIdentifier } from "./traveleridentifier";
import { Expose, Type } from "class-transformer";

export class PrimaryContact extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "@type" })
    atType: string;

    /**
     * Electronic email addresses, in IETF specified format.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "Email" })
    @Type(() => Email)
    email?: Email;

    @SpeakeasyMetadata()
    @Expose({ name: "Telephone" })
    @Type(() => Telephone)
    telephone?: Telephone;

    @SpeakeasyMetadata()
    @Expose({ name: "TravelerIdentifier" })
    @Type(() => TravelerIdentifier)
    travelerIdentifier?: TravelerIdentifier;

    /**
     * If true, the passenger has refused to provide emergency contact details
     */
    @SpeakeasyMetadata()
    @Expose({ name: "contactInformationRefusedInd" })
    contactInformationRefusedInd?: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id?: string;

    /**
     * Share with like Supplier,agency etc
     */
    @SpeakeasyMetadata()
    @Expose({ name: "shareWith" })
    shareWith?: ShareWithEnum;

    /**
     * Primary contact shared with supplier
     */
    @SpeakeasyMetadata()
    @Expose({ name: "shareWithSupplier" })
    shareWithSupplier?: string[];
}
