/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { PropertiesResponse } from "./propertiesresponse";
import { Expose, Type } from "class-transformer";

export class PropertiesResponseWrapper extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "PropertiesResponse" })
    @Type(() => PropertiesResponse)
    propertiesResponse?: PropertiesResponse;
}
