/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { PropertiesQuerySpecificPropertyList } from "./propertiesqueryspecificpropertylist";
import { Expose, Type } from "class-transformer";

export class PropertiesQuerySpecificPropertyListWrapper extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "PropertiesQuerySpecificPropertyList" })
    @Type(() => PropertiesQuerySpecificPropertyList)
    propertiesQuerySpecificPropertyList?: PropertiesQuerySpecificPropertyList;
}
