/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Identifier } from "./identifier";
import { PropertyInfo } from "./propertyinfo";
import { Expose, Type } from "class-transformer";

export class Properties extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "@type" })
    atType: string;

    /**
     * Identifier provides the ability to create a globally unique identifier. For the identifier to be globally unique it must have a system provided identifier and the system must be identified using a global naming authority. System identification uses the domain naming system (DNS) to assure they are globally unique and should be an URL. The system provided ID will typically be a primary or surrogate key in a database.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "Identifier" })
    @Type(() => Identifier)
    identifier?: Identifier;

    @SpeakeasyMetadata({ elemType: PropertyInfo })
    @Expose({ name: "PropertyInfo" })
    @Type(() => PropertyInfo)
    propertyInfo: PropertyInfo[];

    /**
     * Number of properties per page
     */
    @SpeakeasyMetadata()
    @Expose({ name: "propertiesPerPage" })
    propertiesPerPage?: number;

    /**
     * Total number or properties returned for the request
     */
    @SpeakeasyMetadata()
    @Expose({ name: "totalProperties" })
    totalProperties?: number;
}
