/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { RFCDate } from "../../../sdk/types";
import { ImageSizeEnum } from "./imagesizeenum";
import { PropertyKey } from "./propertykey";
import { RateCandidates } from "./ratecandidates";
import { RoomStayCandidates } from "./roomstaycandidates";
import { Expose, Transform, Type } from "class-transformer";

export class PropertiesQuerySpecificPropertyList extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "@type" })
    atType: string;

    @SpeakeasyMetadata({ elemType: PropertyKey })
    @Expose({ name: "PropertyKey" })
    @Type(() => PropertyKey)
    propertyKey: PropertyKey[];

    @SpeakeasyMetadata()
    @Expose({ name: "RateCandidates" })
    @Type(() => RateCandidates)
    rateCandidates?: RateCandidates;

    @SpeakeasyMetadata()
    @Expose({ name: "RoomStayCandidates" })
    @Type(() => RoomStayCandidates)
    roomStayCandidates?: RoomStayCandidates;

    /**
     * Checkin date
     */
    @SpeakeasyMetadata()
    @Expose({ name: "checkinDate" })
    @Type(() => String)
    @Transform(({ value }) => new RFCDate(value), { toClassOnly: true })
    checkinDate: RFCDate;

    /**
     * Checkout date
     */
    @SpeakeasyMetadata()
    @Expose({ name: "checkoutDate" })
    @Type(() => String)
    @Transform(({ value }) => new RFCDate(value), { toClassOnly: true })
    checkoutDate: RFCDate;

    /**
     * Indicates the size of the image. Hospitality APIs no longer support thumbnail
     */
    @SpeakeasyMetadata()
    @Expose({ name: "imageSize" })
    imageSize?: ImageSizeEnum;

    /**
     * Maximum rate
     */
    @SpeakeasyMetadata()
    @Expose({ name: "maximumRate" })
    maximumRate?: number;

    /**
     * Minimum rate
     */
    @SpeakeasyMetadata()
    @Expose({ name: "minimumRate" })
    minimumRate?: number;

    /**
     * Number of travelers. Must be a numeric value between 1 and 9.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "numberOfGuests" })
    numberOfGuests: number;

    /**
     * Number of rooms
     */
    @SpeakeasyMetadata()
    @Expose({ name: "numberOfRooms" })
    numberOfRooms?: number;

    /**
     * You can use requested currency to request conversion rate information. The response will return the currencyRateConversion object which will contain conversion rate of the requested currency.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "requestedCurrency" })
    requestedCurrency?: string;

    /**
     * If true, all property images of the size requested will be returned. If blank or false the best single property image will be returned.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "returnAllImagesInd" })
    returnAllImagesInd?: boolean;
}
