/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { PropertyKey } from "./propertykey";
import { Expose, Type } from "class-transformer";

export class PropertyRequest extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "@type" })
    atType?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "PropertyKey" })
    @Type(() => PropertyKey)
    propertyKey: PropertyKey;

    /**
     * More rates token
     */
    @SpeakeasyMetadata()
    @Expose({ name: "moreRatesToken" })
    moreRatesToken?: string;
}
