/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Address } from "./address";
import { Attraction } from "./attraction";
import { CheckInOutPolicy } from "./checkinoutpolicy";
import { GeoLocation } from "./geolocation";
import { GuestRoomInfo } from "./guestroominfo";
import { Identifier } from "./identifier";
import { Image } from "./image";
import { MeetingRooms } from "./meetingrooms";
import { OTACodeWithDescription } from "./otacodewithdescription";
import { PetPolicy } from "./petpolicy";
import { PropertyAmenity } from "./propertyamenity";
import { PropertyKey } from "./propertykey";
import { Rating } from "./rating";
import { Restaurant } from "./restaurant";
import { Service } from "./service";
import { TextFree } from "./textfree";
import { VirtualTour } from "./virtualtour";
import { YesNoUnknownEnum } from "./yesnounknownenum";
import { Expose, Type } from "class-transformer";

export class PropertyDetail extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "@type" })
    atType: string;

    @SpeakeasyMetadata({ elemType: OTACodeWithDescription })
    @Expose({ name: "AccessibilityFeature" })
    @Type(() => OTACodeWithDescription)
    accessibilityFeature?: OTACodeWithDescription[];

    @SpeakeasyMetadata()
    @Expose({ name: "Address" })
    @Type(() => Address)
    address?: Address;

    @SpeakeasyMetadata({ elemType: Attraction })
    @Expose({ name: "Attraction" })
    @Type(() => Attraction)
    attraction?: Attraction[];

    @SpeakeasyMetadata({ elemType: Service })
    @Expose({ name: "BusinessService" })
    @Type(() => Service)
    businessService?: Service[];

    @SpeakeasyMetadata()
    @Expose({ name: "CheckInOutPolicy" })
    @Type(() => CheckInOutPolicy)
    checkInOutPolicy?: CheckInOutPolicy;

    @SpeakeasyMetadata()
    @Expose({ name: "Description" })
    description?: string[];

    /**
     * Textual information to provide descriptions and\/or additional information.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "DrivingDirections" })
    @Type(() => TextFree)
    drivingDirections?: TextFree;

    /**
     * Used to specify the geographic coordinates of a location
     */
    @SpeakeasyMetadata()
    @Expose({ name: "GeoLocation" })
    @Type(() => GeoLocation)
    geoLocation?: GeoLocation;

    @SpeakeasyMetadata({ elemType: GuestRoomInfo })
    @Expose({ name: "GuestRoomInfo" })
    @Type(() => GuestRoomInfo)
    guestRoomInfo?: GuestRoomInfo[];

    /**
     * Identifier provides the ability to create a globally unique identifier. For the identifier to be globally unique it must have a system provided identifier and the system must be identified using a global naming authority. System identification uses the domain naming system (DNS) to assure they are globally unique and should be an URL. The system provided ID will typically be a primary or surrogate key in a database.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "Identifier" })
    @Type(() => Identifier)
    identifier?: Identifier;

    @SpeakeasyMetadata({ elemType: Image })
    @Expose({ name: "Image" })
    @Type(() => Image)
    image?: Image[];

    @SpeakeasyMetadata()
    @Expose({ name: "MeetingRooms" })
    @Type(() => MeetingRooms)
    meetingRooms?: MeetingRooms;

    @SpeakeasyMetadata()
    @Expose({ name: "PetPolicy" })
    @Type(() => PetPolicy)
    petPolicy?: PetPolicy;

    @SpeakeasyMetadata({ elemType: PropertyAmenity })
    @Expose({ name: "PropertyAmenity" })
    @Type(() => PropertyAmenity)
    propertyAmenity?: PropertyAmenity[];

    @SpeakeasyMetadata()
    @Expose({ name: "PropertyKey" })
    @Type(() => PropertyKey)
    propertyKey: PropertyKey;

    @SpeakeasyMetadata({ elemType: Rating })
    @Expose({ name: "Rating" })
    @Type(() => Rating)
    rating?: Rating[];

    @SpeakeasyMetadata({ elemType: Restaurant })
    @Expose({ name: "Restaurant" })
    @Type(() => Restaurant)
    restaurant?: Restaurant[];

    @SpeakeasyMetadata()
    @Expose({ name: "Telephone" })
    telephone?: string[];

    @SpeakeasyMetadata()
    @Expose({ name: "VirtualTour" })
    @Type(() => VirtualTour)
    virtualTour?: VirtualTour;

    /**
     * The OTA code of the property detail
     */
    @SpeakeasyMetadata()
    @Expose({ name: "classTypeCode" })
    classTypeCode?: string;

    /**
     * Yes , No , Unknown
     */
    @SpeakeasyMetadata()
    @Expose({ name: "complimentaryParking" })
    complimentaryParking?: YesNoUnknownEnum;

    /**
     * Local reference id.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id?: string;

    /**
     * Location category code
     */
    @SpeakeasyMetadata()
    @Expose({ name: "locationCatagoryCode" })
    locationCatagoryCode?: string;

    /**
     * The property name
     */
    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name: string;

    /**
     * Segment category code
     */
    @SpeakeasyMetadata()
    @Expose({ name: "segmentCatagoryCode" })
    segmentCatagoryCode?: string;
}
