/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class PropertyKey extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "@type" })
    atType?: string;

    /**
     * Chain code for the property.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "chainCode" })
    chainCode: string;

    /**
     * Code for the property within the hotel chain.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "propertyCode" })
    propertyCode: string;
}
