/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { PropertiesQueryPrecisionSearch } from "./propertiesqueryprecisionsearch";
import { Expose, Type } from "class-transformer";

export class PropertiesQueryPrecisionSearchWrapper extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "PropertiesQuerySearch" })
    @Type(() => PropertiesQueryPrecisionSearch)
    propertiesQuerySearch?: PropertiesQueryPrecisionSearch;
}
