/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { OperationTimes } from "./operationtimes";
import { Expose, Type } from "class-transformer";

export class PropertyAmenity extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "@type" })
    atType?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "Inclusion" })
    inclusion?: string[];

    /**
     * Name of the property
     */
    @SpeakeasyMetadata()
    @Expose({ name: "Name" })
    name?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "OperationTimes" })
    @Type(() => OperationTimes)
    operationTimes?: OperationTimes;

    /**
     * OTA code used to describe the property amenity.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "code" })
    code?: string;

    /**
     * Type of amenity.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "description" })
    description?: string;

    /**
     * To represent if the Amenity is included in the rate
     */
    @SpeakeasyMetadata()
    @Expose({ name: "includedInd" })
    includedInd?: boolean;

    /**
     * Location of the property
     */
    @SpeakeasyMetadata()
    @Expose({ name: "location" })
    location?: string;

    /**
     * To represent if the Amenity attracts a surcharge
     */
    @SpeakeasyMetadata()
    @Expose({ name: "surchargeInd" })
    surchargeInd?: boolean;
}
