/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { PropertiesQuerySearch } from "./propertiesquerysearch";
import { Expose, Type } from "class-transformer";

export class PropertiesQuerySearchWrapper extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "PropertiesQuerySearch" })
    @Type(() => PropertiesQuerySearch)
    propertiesQuerySearch?: PropertiesQuerySearch;
}
