/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

export enum PurposeEnum {
    Business = "Business",
    Pleasure = "Pleasure",
    CharterService = "Charter Service",
}
