/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { RateCandidate } from "./ratecandidate";
import { Expose, Type } from "class-transformer";

export class RateCandidates extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "@type" })
    atType: string;

    @SpeakeasyMetadata({ elemType: RateCandidate })
    @Expose({ name: "RateCandidate" })
    @Type(() => RateCandidate)
    rateCandidate: RateCandidate[];

    /**
     * If true, only postpay rates will be returned
     */
    @SpeakeasyMetadata()
    @Expose({ name: "postPayRatesOnlyInd" })
    postPayRatesOnlyInd?: boolean;

    /**
     * If true, only prepay rates will be returned
     */
    @SpeakeasyMetadata()
    @Expose({ name: "prePayRatesOnlyInd" })
    prePayRatesOnlyInd?: boolean;
}
