/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { RateCategoryEnum } from "./ratecategoryenum";
import { Expose } from "class-transformer";

export class RateCandidate extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "@type" })
    atType: string;

    /**
     * The hotel chain code
     */
    @SpeakeasyMetadata()
    @Expose({ name: "chainCode" })
    chainCode?: string;

    /**
     * rate candidate priority
     */
    @SpeakeasyMetadata()
    @Expose({ name: "priority" })
    priority?: number;

    /**
     * The hotel chain code
     */
    @SpeakeasyMetadata()
    @Expose({ name: "propertyCode" })
    propertyCode?: string;

    /**
     * Rate Category
     */
    @SpeakeasyMetadata()
    @Expose({ name: "rateCategory" })
    rateCategory?: RateCategoryEnum;

    /**
     * The rateCode to be applied to the request
     */
    @SpeakeasyMetadata()
    @Expose({ name: "rateCode" })
    rateCode?: string;
}
