/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * The actual award or rating received by the facility.
 */
export class Rating extends SpeakeasyBase {
    /**
     * The provider who has granted the quality rating
     */
    @SpeakeasyMetadata()
    @Expose({ name: "provider" })
    provider?: string;

    /**
     * Rating used to classify hotels according to the quality
     */
    @SpeakeasyMetadata()
    @Expose({ name: "value" })
    value?: number;
}
