/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Identifier } from "./identifier";
import { Expose, Transform, Type } from "class-transformer";

export class Receipt extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "@type" })
    atType: string;

    /**
     * Identifier provides the ability to create a globally unique identifier. For the identifier to be globally unique it must have a system provided identifier and the system must be identified using a global naming authority. System identification uses the domain naming system (DNS) to assure they are globally unique and should be an URL. The system provided ID will typically be a primary or surrogate key in a database.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "Identifier" })
    @Type(() => Identifier)
    identifier?: Identifier;

    /**
     * List of offers which links with the receipt
     */
    @SpeakeasyMetadata()
    @Expose({ name: "OfferRef" })
    offerRef?: string[];

    /**
     * Reference of product
     */
    @SpeakeasyMetadata()
    @Expose({ name: "ProductRef" })
    productRef?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "ReceiptRef" })
    receiptRef?: string;

    /**
     * Receipt date time
     */
    @SpeakeasyMetadata()
    @Expose({ name: "dateTime" })
    @Transform(({ value }) => new Date(value), { toClassOnly: true })
    dateTime?: Date;

    /**
     * The verification number.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id?: string;
}
