/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { ReservationQueryBuild } from "./reservationquerybuild";
import { Expose, Type } from "class-transformer";

export class ReservationQueryBuildWrapper extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "ReservationQueryBuild" })
    @Type(() => ReservationQueryBuild)
    reservationQueryBuild?: ReservationQueryBuild;
}
