/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { ReservationDetail } from "./reservationdetail";
import { Expose, Type } from "class-transformer";

export class ReservationDetailWrapper extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "ReservationDetail" })
    @Type(() => ReservationDetail)
    reservationDetail?: ReservationDetail;
}
