/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { AccountingID } from "./accountingid";
import { DocumentOverridesID } from "./documentoverridesid";
import { FormOfPaymentID } from "./formofpaymentid";
import { PaymentID } from "./paymentid";
import { PreferenceID } from "./preferenceid";
import { PrimaryContactID } from "./primarycontactid";
import { ReceiptConfirmation } from "./receiptconfirmation";
import { ReservationCommentID } from "./reservationcommentid";
import { SpecialServiceID } from "./specialserviceid";
import { TravelAgency } from "./travelagency";
import { TravelerID } from "./travelerid";
import { Expose, Type } from "class-transformer";

export class ReservationBuild extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "@type" })
    atType: string;

    @SpeakeasyMetadata()
    @Expose({ name: "Accounting" })
    @Type(() => AccountingID)
    accounting?: AccountingID;

    @SpeakeasyMetadata({ elemType: DocumentOverridesID })
    @Expose({ name: "DocumentOverrides" })
    @Type(() => DocumentOverridesID)
    documentOverrides?: DocumentOverridesID[];

    @SpeakeasyMetadata({ elemType: FormOfPaymentID })
    @Expose({ name: "FormOfPayment" })
    @Type(() => FormOfPaymentID)
    formOfPayment?: FormOfPaymentID[];

    @SpeakeasyMetadata({ elemType: PaymentID })
    @Expose({ name: "Payment" })
    @Type(() => PaymentID)
    payment?: PaymentID[];

    @SpeakeasyMetadata({ elemType: PreferenceID })
    @Expose({ name: "Preference" })
    @Type(() => PreferenceID)
    preference?: PreferenceID[];

    @SpeakeasyMetadata({ elemType: PrimaryContactID })
    @Expose({ name: "PrimaryContact" })
    @Type(() => PrimaryContactID)
    primaryContact?: PrimaryContactID[];

    @SpeakeasyMetadata()
    @Expose({ name: "ReceiptConfirmation" })
    @Type(() => ReceiptConfirmation)
    receiptConfirmation?: ReceiptConfirmation;

    @SpeakeasyMetadata({ elemType: ReservationCommentID })
    @Expose({ name: "ReservationComment" })
    @Type(() => ReservationCommentID)
    reservationComment?: ReservationCommentID[];

    @SpeakeasyMetadata({ elemType: SpecialServiceID })
    @Expose({ name: "SpecialService" })
    @Type(() => SpecialServiceID)
    specialService?: SpecialServiceID[];

    @SpeakeasyMetadata()
    @Expose({ name: "TravelAgency" })
    @Type(() => TravelAgency)
    travelAgency?: TravelAgency;

    @SpeakeasyMetadata({ elemType: TravelerID })
    @Expose({ name: "Traveler" })
    @Type(() => TravelerID)
    traveler: TravelerID[];
}
