/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { ReservationResponse } from "./reservationresponse";
import { Expose, Type } from "class-transformer";

export class ReservationResponseWrapper extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "ReservationResponse" })
    @Type(() => ReservationResponse)
    reservationResponse?: ReservationResponse;
}
