/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { DisplaySequence } from "./displaysequence";
import { Expose, Type } from "class-transformer";

export class ReservationDisplaySequence extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "@type" })
    atType?: string;

    @SpeakeasyMetadata({ elemType: DisplaySequence })
    @Expose({ name: "DisplaySequence" })
    @Type(() => DisplaySequence)
    displaySequence?: DisplaySequence[];

    /**
     * The sequence of the autoDeleteDate (retention segment) within the Reservation
     */
    @SpeakeasyMetadata()
    @Expose({ name: "autoDeleteDateSequence" })
    autoDeleteDateSequence?: number;
}
