/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { DocumentTypeEnum } from "./documenttypeenum";
import { TravelerIdentifierRef } from "./traveleridentifierref";
import { Expose, Type } from "class-transformer";

export class Restrictions extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "@type" })
    atType?: string;

    /**
     * Document type like EMD, MCO
     */
    @SpeakeasyMetadata()
    @Expose({ name: "DocumentType" })
    documentType?: DocumentTypeEnum;

    @SpeakeasyMetadata()
    @Expose({ name: "Restriction" })
    restriction: string[];

    @SpeakeasyMetadata({ elemType: TravelerIdentifierRef })
    @Expose({ name: "TravelerIdentifierRef" })
    @Type(() => TravelerIdentifierRef)
    travelerIdentifierRef?: TravelerIdentifierRef[];
}
