/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * The status of an error or warning
 */
export enum ResultStatusEnum {
    NotProcessed = "Not processed",
    Incomplete = "Incomplete",
    Complete = "Complete",
    Unknown = "Unknown",
}
