/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class RoomAmenity extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "@type" })
    atType?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "Inclusion" })
    inclusion?: string[];

    /**
     * Room Amenity Name
     */
    @SpeakeasyMetadata()
    @Expose({ name: "Name" })
    name?: string;

    /**
     * OTA code used to describe the room amenity. This is optional in the Properties Search request but mandatory in the response
     */
    @SpeakeasyMetadata()
    @Expose({ name: "code" })
    code?: string;

    /**
     * description of the room amenity
     */
    @SpeakeasyMetadata()
    @Expose({ name: "description" })
    description?: string;

    /**
     * To represent if the Amenity is included in the rate
     */
    @SpeakeasyMetadata()
    @Expose({ name: "includedInd" })
    includedInd?: boolean;

    /**
     * quantity of amenity
     */
    @SpeakeasyMetadata()
    @Expose({ name: "quantity" })
    quantity?: number;

    /**
     * To represent if the Amenity attracts a surcharge
     */
    @SpeakeasyMetadata()
    @Expose({ name: "surchargeInd" })
    surchargeInd?: boolean;
}
