/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { RoomStayCandidate } from "./roomstaycandidate";
import { Expose, Type } from "class-transformer";

export class RoomStayCandidates extends SpeakeasyBase {
    @SpeakeasyMetadata({ elemType: RoomStayCandidate })
    @Expose({ name: "RoomStayCandidate" })
    @Type(() => RoomStayCandidate)
    roomStayCandidate: RoomStayCandidate[];
}
