/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class SearchControlConsoleChannelID extends SpeakeasyBase {
    /**
     * Assigned Type: c-1100:StringTiny
     */
    @SpeakeasyMetadata()
    @Expose({ name: "sccType" })
    sccType?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "value" })
    value?: string;
}
