/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * A business service offered by the property
 */
export class Service extends SpeakeasyBase {
    /**
     * OTA code for this service type.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "code" })
    code?: string;

    /**
     * Description of the service
     */
    @SpeakeasyMetadata()
    @Expose({ name: "description" })
    description?: string;

    /**
     * If present and true this service exists
     */
    @SpeakeasyMetadata()
    @Expose({ name: "existsInd" })
    existsInd?: boolean;

    /**
     * If present and true this service is included with no charge
     */
    @SpeakeasyMetadata()
    @Expose({ name: "includedInd" })
    includedInd?: boolean;

    /**
     * Proximity code
     */
    @SpeakeasyMetadata()
    @Expose({ name: "proximityCode" })
    proximityCode?: string;
}
