/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * Share with like Supplier,agency etc
 */
export enum ShareWithEnum {
    Supplier = "Supplier",
    Agency = "Agency",
    Traveler = "Traveler",
}
