/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { ProductAir } from "./productair";
import { Expose, Type } from "class-transformer";

export class ShoppingCart extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "@type" })
    atType?: string;

    @SpeakeasyMetadata({ elemType: ProductAir })
    @Expose({ name: "Product" })
    @Type(() => ProductAir)
    product?: ProductAir[];
}
