/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { CurrencyCode } from "./currencycode";
import { Expose, Type } from "class-transformer";

export class TaxBreakdown extends SpeakeasyBase {
    /**
     * The airport location the tax applies to
     */
    @SpeakeasyMetadata()
    @Expose({ name: "AirportCode" })
    airportCode: string;

    /**
     * The amount of the tax applied
     */
    @SpeakeasyMetadata()
    @Expose({ name: "Amount" })
    amount?: number;

    /**
     * Currency codes are the three-letter alphabetic codes that represent the various currencies used throughout the world.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "CurrencyCode" })
    @Type(() => CurrencyCode)
    currencyCode?: CurrencyCode;
}
