/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { TaxInfo } from "./taxinfo";
import { Expose, Type } from "class-transformer";

export class Taxes extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "@type" })
    atType: string;

    @SpeakeasyMetadata({ elemType: TaxInfo })
    @Expose({ name: "TaxInfo" })
    @Type(() => TaxInfo)
    taxInfo?: TaxInfo[];

    /**
     * A monetary amount, up to 4 decimal places. Decimal place needs to be included.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "TotalTaxes" })
    totalTaxes?: number;
}
