/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { CurrencyCode } from "./currencycode";
import { TaxBreakdown } from "./taxbreakdown";
import { Expose, Type } from "class-transformer";

export class TaxInfo extends SpeakeasyBase {
    /**
     * The amount of the tax applied
     */
    @SpeakeasyMetadata()
    @Expose({ name: "Amount" })
    amount: number;

    /**
     * Currency codes are the three-letter alphabetic codes that represent the various currencies used throughout the world.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "CurrencyCode" })
    @Type(() => CurrencyCode)
    currencyCode?: CurrencyCode;

    /**
     * The breakdown of the tax for this tax code
     */
    @SpeakeasyMetadata({ elemType: TaxBreakdown })
    @Expose({ name: "TaxBreakdown" })
    @Type(() => TaxBreakdown)
    taxBreakdown: TaxBreakdown[];

    /**
     * The tax code
     */
    @SpeakeasyMetadata()
    @Expose({ name: "TaxCode" })
    taxCode: string;
}
