/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { EnumTelephoneRole } from "./enumtelephonerole";
import { Expose } from "class-transformer";

export class Telephone extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "@type" })
    atType: string;

    /**
     * Telephone Area CityCode
     */
    @SpeakeasyMetadata()
    @Expose({ name: "areaCityCode" })
    areaCityCode?: string;

    /**
     * City Code
     */
    @SpeakeasyMetadata()
    @Expose({ name: "cityCode" })
    cityCode?: string;

    /**
     * TelephoneCountry AccessCode
     */
    @SpeakeasyMetadata()
    @Expose({ name: "countryAccessCode" })
    countryAccessCode?: string;

    /**
     * Telephone extension number
     */
    @SpeakeasyMetadata()
    @Expose({ name: "extension" })
    extension?: string;

    /**
     * UOptional internally referenced id
     */
    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id?: string;

    /**
     * Mobile/Telephone Number
     */
    @SpeakeasyMetadata()
    @Expose({ name: "phoneNumber" })
    phoneNumber: string;

    @SpeakeasyMetadata()
    @Expose({ name: "role" })
    role?: EnumTelephoneRole;
}
