/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { TextFormatEnum } from "./textformatenum";
import { Expose } from "class-transformer";

/**
 * Provides text and indicates whether it is formatted or not.
 */
export class TextFormatted extends SpeakeasyBase {
    /**
     * The language in which the text is provided.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "language" })
    language?: string;

    /**
     * Describes the format of text such as plain text or html
     */
    @SpeakeasyMetadata()
    @Expose({ name: "textFormat" })
    textFormat?: TextFormatEnum;

    @SpeakeasyMetadata()
    @Expose({ name: "value" })
    value?: string;
}
