/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * Describes the format of text such as plain text or html
 */
export enum TextFormatEnum {
    PlainText = "PlainText",
    Html = "HTML",
}
