/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * Descriptive text
 */
export class TextTitleAndDescription extends SpeakeasyBase {
    /**
     * Language of the text
     */
    @SpeakeasyMetadata()
    @Expose({ name: "languages" })
    languages?: string[];

    /**
     * Title of the Text
     */
    @SpeakeasyMetadata()
    @Expose({ name: "title" })
    title?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "value" })
    value?: string;
}
