/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * Textual information to provide descriptions and\/or additional information.
 */
export class TextFree extends SpeakeasyBase {
    /**
     * Language of the text.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "language" })
    language?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "value" })
    value?: string;
}
