/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { TourCodeTypeEnum } from "./tourcodetypeenum";
import { Expose } from "class-transformer";

/**
 * Tour code
 */
export class TourCode extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "tourCodeType" })
    tourCodeType?: TourCodeTypeEnum;

    @SpeakeasyMetadata()
    @Expose({ name: "value" })
    value?: string;
}
