/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { TourCode } from "./tourcode";
import { TravelerIdentifierRef } from "./traveleridentifierref";
import { Expose, Type } from "class-transformer";

export class TourCodes extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "@type" })
    atType?: string;

    /**
     * Tour code
     */
    @SpeakeasyMetadata()
    @Expose({ name: "TourCode" })
    @Type(() => TourCode)
    tourCode: TourCode;

    @SpeakeasyMetadata({ elemType: TravelerIdentifierRef })
    @Expose({ name: "TravelerIdentifierRef" })
    @Type(() => TravelerIdentifierRef)
    travelerIdentifierRef?: TravelerIdentifierRef[];
}
