/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { CompanyName } from "./companyname";
import { Identifier } from "./identifier";
import { OrganizationTypeEnum } from "./organizationtypeenum";
import { Expose, Type } from "class-transformer";

export class TravelAgency extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "@type" })
    atType: string;

    /**
     * A reference assigned by the Travel Agency to identify the corporate organization
     */
    @SpeakeasyMetadata()
    @Expose({ name: "CorporateCode" })
    corporateCode?: string;

    /**
     * Identifier provides the ability to create a globally unique identifier. For the identifier to be globally unique it must have a system provided identifier and the system must be identified using a global naming authority. System identification uses the domain naming system (DNS) to assure they are globally unique and should be an URL. The system provided ID will typically be a primary or surrogate key in a database.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "Identifier" })
    @Type(() => Identifier)
    identifier?: Identifier;

    /**
     * Identifies a company by name.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "OrganizationName" })
    @Type(() => CompanyName)
    organizationName: CompanyName;

    @SpeakeasyMetadata()
    @Expose({ name: "ProfileName" })
    profileName?: string[];

    /**
     * An organization that has a name and a structure and members and directly works in the travel industry
     */
    @SpeakeasyMetadata()
    @Expose({ name: "TravelOrganizationRef" })
    travelOrganizationRef?: string;

    /**
     * Simple xsd id, not for external use
     */
    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id?: string;

    /**
     * The type of organization such as an Agency, Branch, Company, Supplier, Provider
     */
    @SpeakeasyMetadata()
    @Expose({ name: "organizationType" })
    organizationType?: OrganizationTypeEnum;
}
