/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { ConfirmationStatusEnum } from "./confirmationstatusenum";
import { Expose } from "class-transformer";

export class TravelerProduct extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "@type" })
    atType: string;

    /**
     * Status returned in a response for a two or more phase commitment process
     */
    @SpeakeasyMetadata()
    @Expose({ name: "ConfirmationStatusEnum" })
    confirmationStatusEnum?: ConfirmationStatusEnum;

    /**
     * A pointer to the Offer id
     */
    @SpeakeasyMetadata()
    @Expose({ name: "OfferRef" })
    offerRef?: string;

    /**
     * A pointer to the product id
     */
    @SpeakeasyMetadata()
    @Expose({ name: "ProductRef" })
    productRef?: string;

    /**
     * A pointer to the traveler id
     */
    @SpeakeasyMetadata()
    @Expose({ name: "TravelerRef" })
    travelerRef?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id?: string;
}
