/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class TravelerIdentifierRef extends SpeakeasyBase {
    /**
     * Descriptive text used to identify the contents of a target object
     */
    @SpeakeasyMetadata()
    @Expose({ name: "description" })
    description?: string;

    /**
     * A locally referenced ID
     */
    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id?: string;

    /**
     * Traveler identifier
     */
    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name?: string;

    /**
     * Passenger Type code
     */
    @SpeakeasyMetadata()
    @Expose({ name: "passengerTypeCode" })
    passengerTypeCode?: string;

    /**
     * Uniform Resource Identifier
     */
    @SpeakeasyMetadata()
    @Expose({ name: "uris" })
    uris?: string[];

    @SpeakeasyMetadata()
    @Expose({ name: "value" })
    value?: string;
}
