/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * The unit of measure in a code format. Refer to OpenTravel Code List Unit of Measure Code (UOM).
 */
export enum UnitOfMeasureEnum {
    Miles = "Miles",
    Kilometers = "Kilometers",
    Meters = "Meters",
    Millimeters = "Millimeters",
    Centimeters = "Centimeters",
    Yards = "Yards",
    Feet = "Feet",
    Inches = "Inches",
    Pixels = "Pixels",
    Block = "Block",
    Megabytes = "Megabytes",
    Gigabytes = "Gigabytes",
    SquareFeet = "Square feet",
    SquareMeters = "Square meters",
    Pounds = "Pounds",
    Kilograms = "Kilograms",
    SquareInch = "Square inch",
    SquareYard = "Square yard",
    Acre = "Acre",
    SquareMillimeter = "Square millimeter",
    SquareCentimeter = "Square centimeter",
    Hectare = "Hectare",
    Ounce = "Ounce",
    Gram = "Gram",
    Gallons = "Gallons",
    Liters = "Liters",
    Kilowatts = "Kilowatts",
    CubicMeters = "Cubic meters",
}
