/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * List of units of size i.e Square Feet, Square Meters
 */
export enum UnitOfSize {
    SquareFeet = "Square Feet",
    SquareMeters = "Square Meters",
}
