/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * Miles, Kilometers, etc.
 */
export enum UnitOfDistanceEnum {
    Miles = "Miles",
    Kilometers = "Kilometers",
}
