/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { TextFree } from "./textfree";
import { Expose, Type } from "class-transformer";

export class VirtualTour extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "@type" })
    atType?: string;

    /**
     * Textual information to provide descriptions and\/or additional information.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "Description" })
    @Type(() => TextFree)
    description?: TextFree;

    @SpeakeasyMetadata()
    @Expose({ name: "url" })
    url: string;
}
