/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * Yes , No , Unknown
 */
export enum YesNoUnknownEnum {
    Yes = "Yes",
    No = "No",
    Unknown = "Unknown",
}
