/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * Used to indicate marketing preferences, Yes, No, Inherit
 */
export enum YesNoInheritEnum {
    Yes = "Yes",
    No = "No",
    Inherit = "Inherit",
}
