/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyMetadata } from "../../../internal/utils";
import { classToPlain, Expose, Transform } from "class-transformer";

/**
 * A conversion metric from standard to another with the contextual authority such as IATA, OAG, ISO, etc.
 */
export class ConversionRate extends Error {
    /**
     * Rate as of
     */
    @SpeakeasyMetadata()
    @Expose({ name: "rateAsOf" })
    @Transform(({ value }) => new Date(value), { toClassOnly: true })
    rateAsOf?: Date;

    /**
     * Rate authority
     */
    @SpeakeasyMetadata()
    @Expose({ name: "rateAuthority" })
    rateAuthority?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "value" })
    value?: number;

    constructor(err?: ConversionRate) {
        super();
        if (err) {
            Object.assign(this, err);
            this.message = JSON.stringify(
                classToPlain(err, { exposeUnsetFields: false, excludeExtraneousValues: true })
            );
        }

        this.name = "ConversionRate";
        Object.setPrototypeOf(this, ConversionRate.prototype);
    }
}
