/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyMetadata } from "../../../internal/utils";
import { classToPlain, Expose } from "class-transformer";

export class ReferenceList extends Error {
    @SpeakeasyMetadata()
    @Expose({ name: "@type" })
    atType: string;

    /**
     * Uniquely identifies for the Reference List
     */
    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id?: string;

    constructor(err?: ReferenceList) {
        super();
        if (err) {
            Object.assign(this, err);
            this.message = JSON.stringify(
                classToPlain(err, { exposeUnsetFields: false, excludeExtraneousValues: true })
            );
        }

        this.name = "ReferenceList";
        Object.setPrototypeOf(this, ReferenceList.prototype);
    }
}
