/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../../../sdk/models/shared";
import { AxiosResponse } from "axios";

export class GetPropertiesPageRequest extends SpeakeasyBase {
    /**
     * Identifier used to correlate API invocations across long-running or multi-call business flows.
     */
    @SpeakeasyMetadata({ data: "header, style=simple;explode=false;name=TraceId" })
    traceId?: string;

    /**
     * Identifies the Travelport access group with which the caller is associated
     */
    @SpeakeasyMetadata({
        data: "header, style=simple;explode=false;name=XAUTH_TRAVELPORT_ACCESSGROUP",
    })
    xauthTravelportAccessgroup?: string;

    /**
     * The Identifier of the Properties from which a page is to be returned
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=identifier" })
    identifier: string;

    /**
     * The page number to be returned
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=pageNumber" })
    pageNumber: string;
}

export class GetPropertiesPageResponse extends SpeakeasyBase {
    /**
     * HTTP response content type for this operation
     */
    @SpeakeasyMetadata()
    contentType: string;

    /**
     * OK - Successful Response - 200
     */
    @SpeakeasyMetadata()
    propertiesResponseWrapper?: shared.PropertiesResponseWrapper;

    /**
     * HTTP response status code for this operation
     */
    @SpeakeasyMetadata()
    statusCode: number;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @SpeakeasyMetadata()
    rawResponse: AxiosResponse;
}
