/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";

export class GetPropertiesDetailRequest extends SpeakeasyBase {
    /**
     * The size of the image to be returned
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=ImageSize" })
    imageSize?: shared.ImageSizeEnum;

    /**
     * Identifier used to correlate API invocations across long-running or multi-call business flows.
     */
    @SpeakeasyMetadata({ data: "header, style=simple;explode=false;name=TraceId" })
    traceId?: string;

    /**
     * Identifies the Travelport access group with which the caller is associated
     */
    @SpeakeasyMetadata({
        data: "header, style=simple;explode=false;name=XAUTH_TRAVELPORT_ACCESSGROUP",
    })
    xauthTravelportAccessgroup?: string;

    /**
     * Hotel chain code
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=chainCode" })
    chainCode: string;

    /**
     * Property code
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=propertyCode" })
    propertyCode: string;
}

export class GetPropertiesDetailResponse extends SpeakeasyBase {
    /**
     * HTTP response content type for this operation
     */
    @SpeakeasyMetadata()
    contentType: string;

    /**
     * OK - Successful Response - 200
     */
    @SpeakeasyMetadata()
    propertiesResponseWrapper?: shared.PropertiesResponseWrapper;

    /**
     * HTTP response status code for this operation
     */
    @SpeakeasyMetadata()
    statusCode: number;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;
}
